git:
  branchLogCmd: git lf {{branchName}}
  allBranchesLogCmd: git lf
  pull:
    mode: rebase
customCommands:
  - key: "<c-p>"
    context: "localBranches"
    command: "git pull --rebase origin master"
