git:
  branchLogCmd: git lf {{branchName}}
  pull:
    mode: rebase
  allBranchesLogCmds:
    - git lf
customCommands:
  - key: "<c-p>"
    context: "localBranches"
    command: "git pull --rebase origin master"
